### ISSUE TITLE
Wavesのノードを動かしてみる

### ISSUE THREAD

**Issue by shohu** [shohu/Waves#1]
Wavesを調べるためにノードを動かしてみる

masterブランチでは動かないらしいので、releaseブランチ
Version 0.13.0 (Testnet Only)
https://github.com/wavesplatform/Waves/releases
のようなので、こちらを元に構築開始する

## How to install

https://docs.wavesplatform.com/waves-full-node/how-to-install-a-node/how-to-install-a-node.html

## わかりやすい説明

https://coinotaku.com/?p=1125

**Comment by shohu** [comment]
https://docs.wavesplatform.com/waves-full-node/how-to-install-a-node/on-ubuntu.html
の install 手順にしたがってinstallを行ってみる

Ubuntu >= 15.04なので
https://docs.wavesplatform.com/waves-full-node/how-to-install-a-node/on-ubuntu.html#installation-from-systemd-deb-package
をつかう

**Comment by shohu** [comment]
waves deb がうまくインストールできず
```
# dpkg -i waves*.deb
dpkg: error processing archive waves*.deb (--install):
 cannot access archive: No such file or directory
Errors were encountered while processing:
 waves*.deb
```
そりゃdebないからできないわ。
debを作成しよう。
```
Compiling Packages from source
It is only possible to create deb and fat jar packages.
```
Install SBT (Scala Build Tool) で package作るとか、自分は初めてだ。

今日は以下のDockerfile作成してお終い

```
FROM ubuntu:16.04

# init
RUN apt-get update && apt-get install -y \
    software-properties-common && \
    add-apt-repository -y ppa:webupd8team/java && \
    apt-get update && \
    apt-get install -y \
    apt-transport-https

# java
RUN echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | /usr/bin/debconf-set-selections && \
    apt-get install -y \
    oracle-java8-installer

# Scala Build Tool
RUN echo "deb https://dl.bintray.com/sbt/debian /" | tee -a /etc/apt/sources.list.d/sbt.list && \
    apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 2EE0EA64E40A89B84B2DF73499E82A75642AC823 && \
    apt-get update && \
    apt-get install -y sbt

COPY . /waves
WORKDIR /waves

RUN sbt -Dnetwork=testnet packageAll

CMD ["/sbin/init"]
```

**Comment by shohu** [comment]
debファイルを作成するためにcompile。結構時間かかります。
```
# sbt -Dnetwork=testnet packageAll
[info] Loading settings from plugins.sbt ...
[info] Loading project definition from /waves/project
[info] Updating ProjectRef(uri("file:/waves/project/"), "waves-build")...
 :
 :
[info] Adding conffile: lib/systemd/system/waves-testnet.service
[info] Creating changes file: /waves/target/waves-testnet_0.13.0_all.changes
[success] Total time: 63 s, completed May 25, 2018 5:31:59 AM
```
コンパイル成功 !
```
# find . -name "*.deb"
./target/waves-testnet_0.13.0_all.deb
```
debファイルもできたので、いよいよtestnetで起動してみる。
Testは一応やってみるか。

## Test 
Testしてみてうまく動作しているか確認する

```
# sbt test 
 :
 :
[info] Compiling 306 Scala sources to /waves/target/classes ...

[info] Done compiling.
[info] Formatting 162 Scala sources in node:test ...
[info] Compiling 162 Scala sources to /waves/target/test-classes ...
[info] Done compiling.
 :
 :
[info] - SmartIssueTransaction serialization roundtrip (194 milliseconds)
[info] - JSON format validation (1 millisecond)
[info] UtilsRouteSpec:
[info] com.wavesplatform.http.UtilsRouteSpec *** ABORTED *** (2 milliseconds)
[info]   java.lang.BootstrapMethodError: call site initialization exception
[info]   at java.lang.invoke.CallSite.makeSite(CallSite.java:341)
[info]   at java.lang.invoke.MethodHandleNatives.linkCallSiteImpl(MethodHandleNatives.java:307)
[info]   at java.lang.invoke.MethodHandleNatives.linkCallSite(MethodHandleNatives.java:297)
[info]   at com.wavesplatform.http.UtilsRouteSpec.<init>(UtilsRouteSpec.scala:78)
 :
 :
```

Error発生

**Comment by shohu** [comment]
install
=====
コンパイルするとtargetディレクトリにdebファイルができるのでこれをインストールしてみる
```
# cd target
# dpkg -i waves*.deb
Selecting previously unselected package waves-testnet.
(Reading database ... 12121 files and directories currently installed.)
Preparing to unpack waves-testnet_0.13.0_all.deb ...
Unpacking waves-testnet (0.13.0) ...
Setting up waves-testnet (0.13.0) ...
Warning: The home dir /var/lib/waves-testnet you specified can't be accessed: No such file or directory
Adding system user `waves-testnet' (UID 106) ...
Adding new group `waves-testnet' (GID 110) ...
Adding new user `waves-testnet' (UID 106) with group `waves-testnet' ...
Not creating home directory `/var/lib/waves-testnet'.
Creating default config file ...
Failed to connect to bus: No such file or directory
Couldn't find an alternative telinit implementation to spawn.
```
Error発生。
```
/var/lib/waves-testnet
```
はディレクトリできていたので
```
Failed to connect to bus: No such file or directory
Couldn't find an alternative telinit implementation to spawn.
```
こちらが原因ぽい。
ぐぐっていると
https://askubuntu.com/questions/813588/systemctl-failed-to-connect-to-bus-docker-ubuntu16-04-container
で
![2018-05-25 14 49 21](https://user-images.githubusercontent.com/1214532/40528164-d97e4b10-602a-11e8-9607-1ccd329c68cf.jpg)
のように述べられていてPID = 1 が systemd じゃないとだめだと。
Dockerを使う方法を再考してはどうかといわれちゃってます。

ただ、privileged を指定してコンテナ起動するとOKらしいのでdocker-composeに以下を追加して起動すると
```
privileged: true
```
以下のようにinstallが成功しました！
```
# dpkg -i waves*.deb
Selecting previously unselected package waves-testnet.
(Reading database ... 8812 files and directories currently installed.)
Preparing to unpack waves-testnet_0.13.0_all.deb ...
Unpacking waves-testnet (0.13.0) ...
Setting up waves-testnet (0.13.0) ...
Warning: The home dir /var/lib/waves-testnet you specified can't be accessed: No such file or directory
Adding system user `waves-testnet' (UID 106) ...
Adding new group `waves-testnet' (GID 108) ...
Adding new user `waves-testnet' (UID 106) with group `waves-testnet' ...
Not creating home directory `/var/lib/waves-testnet'.
Creating default config file ...
Installing systemd service ...
Created symlink from /etc/systemd/system/multi-user.target.wants/waves-testnet.service to /lib/systemd/system/waves-testnet.service.
```

**Comment by shohu** [comment]
起動
=====
先ほどinstallが成功したが、systemctl で service を起動させようとしたところ起動しないorz
```
# systemctl start waves.service
Failed to start waves.service: Unit waves.service not found.
```
とおもったら、コマンドをtestnet用のものにしないとだめでした
```
# systemctl start waves-testnet.service
# netstat -nao | grep "tcp"
tcp        0      0 127.0.0.1:6886          0.0.0.0:*               LISTEN      off (0.00/0/0)
tcp        0      0 127.0.0.11:36519        0.0.0.0:*               LISTEN      off (0.00/0/0)
tcp        0      0 0.0.0.0:6869            0.0.0.0:*               LISTEN      off (0.00/0/0)
```

**Comment by shohu** [comment]
Walletから独自コインを作成してみる
=====

まずは本番上で挙動確認

https://waveswallet.io/
のページよりアカウント作った。

独自コインは以下右から２つ目のアイコンから。

![2018-05-31 17 33 23](https://user-images.githubusercontent.com/1214532/40771611-c67edc32-64f8-11e8-8a6d-f72813a197b8.jpg)

Beta version https://beta.wavesplatform.com/tokens がありました。

![2018-05-31 17 33 23](https://user-images.githubusercontent.com/1214532/40771874-7f774666-64f9-11e8-94a7-6681d3c44c5e.jpg)

こちらのgithubは https://github.com/wavesplatform/WavesGUI これ。

ノードと GUI があれば開発環境作れる？

**Comment by shohu** [comment]
WavesGUI構築
=====

```
FROM ubuntu:16.04

# init
RUN apt-get update && apt-get install -y \
    software-properties-common \
    curl \
    git \
    nodejs \
    npm

RUN npm cache clean && \
    npm install n -g && \
    n stable && \
    ln -sf /usr/local/bin/node /usr/bin/node

# delete original node
# * If don't execute "bash", can't find npm in path
RUN apt-get purge -y nodejs npm && \
    bash

COPY . /wavesgui
WORKDIR /wavesgui

RUN npm i

CMD ["/sbin/init"]
```
Dockerfile作成した。

**Comment by shohu** [comment]
続きは#2で
